# Generated by Django 4.2 on 2025-03-30 19:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='user_signup',
            name='user_id',
        ),
        migrations.AddField(
            model_name='user_signup',
            name='id',
            field=models.BigAutoField(auto_created=True, default=2, primary_key=True, serialize=False, verbose_name='ID'),
            preserve_default=False,
        ),
    ]
