# Generated by Django 4.2 on 2025-04-03 13:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('mylab', '0002_remove_user_signup_user_id_user_signup_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='user_signup',
            name='reg_date',
            field=models.DateField(null=True),
        ),
    ]
